export const RELATED_LINKS = [
  { label: "Mortgage Affordability Calculator",   href: "https://mortgageaffordabilityestimator.com" },
  { label: "Emergency Savings Calculator",         href: "https://emergencysavingscalculator.com" },
  { label: "Freelancer Rates Calculator",          href: "https://freelancerratescalculator.com" },
  { label: "Credit Card Debt Payoff Calculator",   href: "https://creditcarddebtpayoffcalculator.com" },
  { label: "Debt Reducing Calculator",             href: "https://debtreducingcalculator.com" },
  { label: "Side Hustle Tax Estimator",            href: "https://sidehustletaxestimator.com" },
  { label: "High Yield Savings Calculator",        href: "https://highyieldsavingscalculator.com" },
  { label: "Retirement Savings Gap",               href: "https://retirementsavingsgap.com" },
  { label: "Life Insurance Coverage Calculator",   href: "https://lifeinsurancecoveragecalculator.com" },
  { label: "Online Course ROI Calculator",         href: "https://onlinecourseroi.com" },
  { label: "Subscription Cost Calculator",         href: "https://mysubscriptioncost.com" },
  { label: "Email Attachment Size Checker",        href: "https://emailattachmentsize.com" },
  { label: "GPA Calculator",                       href: "https://gpacalculator.site" },
  { label: "YouTube Title Checker",                href: "https://youtubetitlechecker.com" },
  { label: "Strong Password Builder",              href: "https://strongpasswordbuilder.com" },
  { label: "Cool Username Generator",              href: "https://coolusernamegenerator.com" },
  { label: "MoneyWise Calculator Hub",             href: "https://moneywisecalculator.com" },
]
